apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactions-service
  namespace: project820
  labels:
    app: transactions-service
    project: project820
spec:
  replicas: 2
  selector: # какие поды нужно поддерживать
    matchLabels:
      app: transactions-service
  template: # для подов
    metadata:
      labels:
        app: transactions-service
        project: project820
    spec:
      containers:
        - name: transactions-container
          image: transactions-service:latest
          imagePullPolicy: "Never" # for local in minikube
          ports:
            - containerPort: 8082
          startupProbe:
            tcpSocket:
              port: 8082
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc-health-probe"
                - "-addr=127.0.0.1:8082"
                - "-connect-timeout=1s"
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc-health-probe"
                - "-addr=127.0.0.1:8082"
                - "-connect-timeout=1s"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "1"
  strategy:
    type: RollingUpdate # Recreate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
