apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transactions-service
  namespace: project820
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
spec:
  ingressClassName: nginx
  rules:
    - host: project820.info
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: transactions-service
                port:
                  number: 8082
